document.addEventListener("DOMContentLoaded", () => {
  // ===================================================
  // --- 1. CORE SCRIPT (Original Logic) ---
  // ===================================================

  // --- Data Definition (Brands Only) ---
  const brandLogos = Array.from(
    { length: 12 },
    (_, i) => `images/brands/brand_${i + 1}.png`
  );

  // --- Global Element References ---
  const header = document.querySelector("header");
  const body = document.body;
  const nav = document.querySelector(".navigation");
  const hamburger = document.querySelector(".hamburger-menu");
  const navLinks = document.querySelectorAll(".nav-links li a");
  const brandsCarousel = document.querySelector(".brands-carousel");
  const contactForm = document.getElementById("contact-form");
  const bodyOverlay = document.querySelector(".body-overlay");

  // --- Helper Functions ---
  const createElement = (tag, className, textContent = "") => {
    const element = document.createElement(tag);
    if (className) element.className = className;
    if (textContent) element.textContent = textContent;
    return element;
  };

  const toggleCarouselAnimation = (state) => {
    document
      .querySelectorAll(".brands-row")
      .forEach((row) => (row.style.animationPlayState = state));
  };

  const handleScrollAndMenu = () => {
    if (!header) return;
    const isScrolled = window.scrollY > 50;
    const isNavActive = nav && nav.classList.contains("nav-active");

    header.classList.toggle("header-scrolled", isScrolled);

    // Control body scrolling and overlay based on navigation state
    if (isNavActive) {
      if (bodyOverlay) bodyOverlay.style.opacity = "1";
      body.style.overflow = "hidden";
    } else {
      if (bodyOverlay) bodyOverlay.style.opacity = "0";
      body.style.overflow = "auto";
    }
  };

  const toggleMobileNav = () => {
    if (nav) nav.classList.toggle("nav-active");
    if (hamburger) hamburger.classList.toggle("active");
    handleScrollAndMenu();
  };

  // --- BRANDS POPULATION ---
  const populateBrandsCarousel = () => {
    if (!brandsCarousel) return;

    const createBrandRow = (isReverse = false) => {
      const row = createElement(
        "div",
        `brands-row ${isReverse ? "reverse" : ""}`
      );
      const doubledLogos = [...brandLogos, ...brandLogos];

      doubledLogos.forEach((logo) => {
        const img = createElement("img");
        img.src = logo;
        img.alt = "Brand Logo";
        img.loading = "eager";
        row.appendChild(img);
      });
      return row;
    };
    // NOTE: I am adding the second row back for smoother scrolling, based on best practice.
    brandsCarousel.appendChild(createBrandRow(false));
    // brandsCarousel.appendChild(createBrandRow(true));

    // Pause on Hover for Brands Carousel
    brandsCarousel.addEventListener("mouseenter", () =>
      toggleCarouselAnimation("paused")
    );
    brandsCarousel.addEventListener("mouseleave", () =>
      toggleCarouselAnimation("running")
    );
  };

  // ===================================================
  // --- 2. SERVICE CAROUSEL & MODAL SCRIPT ---
  // (Functions nextSlide and prevSlide are defined globally below)
  // ===================================================
  const servicesData = [
    {
      title: "Residential Solar",
      image: "images/services/residential-solar.jpg",
      info: "We provide custom solar panel installations for homes, designed to meet your energy needs and reduce electricity bills. Our team handles everything from design to permits.",
      icon: "fas fa-home",
    },
    {
      title: "Commercial Solar",
      image: "images/services/commercial-solar.jpg",
      info: "Power your business with sustainable energy. Our commercial solar solutions are scalable and can significantly lower operating costs while enhancing your corporate image.",
      icon: "fas fa-industry",
    },
    {
      title: "Inverter and Battery Solutions",
      image: "images/services/battery-storage.jpg",
      info: "Store excess energy generated by your solar panels with our state-of-the-art battery storage systems. Be prepared for power outages and reduce reliance on the grid.",
      icon: "fas fa-battery-full",
    },
    {
      title: "Solar Panel Maintenance",
      image: "images/services/Maintenance.jpg",
      info: "Regular maintenance is key to the longevity and efficiency of your solar panels. We offer comprehensive cleaning and inspection services to ensure peak performance.",
      icon: "fas fa-wrench",
    },
    {
      title: "Solar Water Heaters",
      image: "images/services/solar-water-heater.jpg",
      info: "Enjoy hot water round the year powered by the sun. Our solar water heaters are efficient, eco-friendly, and help you save electricity costs while providing consistent hot water.",
      icon: "fas fa-fire-alt",
    },
    {
      title: "Solar Fencing",
      image: "images/services/solar-fencing.jpg",
      info: "Secure your property the smart way. Solar fencing offers a safe, durable, and cost-effective solution to protect your land, crops, or property without depending on grid power.",
      icon: "fas fa-bolt",
    },
    {
      title: "Solar Pumps",
      image: "images/services/solar-pump.jpg",
      info: "Smart water pumping with zero electricity bills. Our solar pumps are designed for farmers and agricultural needs. They run directly on solar power, making irrigation easy and cost-effective.",
      icon: "fas fa-water",
    },
  ];

  let currentIndex = 0;
  let autoSlideInterval;
  const carouselTrack = document.getElementById("carouselTrack");
  const indicatorsContainer = document.getElementById("indicators");
  const modal = document.getElementById("serviceModal");

  // Initialize carousel
  const initServiceCarousel = () => {
    servicesData.forEach((service, index) => {
      const card = document.createElement("div");
      card.className = "service-card";
      card.style.setProperty("--card-image-url", `url('${service.image}')`);
      card.innerHTML = `
                <div class="service-card-content">
                    <h3><i class="${service.icon}"></i> ${service.title}</h3>
                    <p>${service.info.substring(0, 100)}...</p>
                    <button class="read-more-btn">Read More</button>
                </div>
            `;
      card.querySelector(".read-more-btn").addEventListener("click", (e) => {
        e.stopPropagation();
        openModal(service);
      });
      carouselTrack.appendChild(card);
    });

    servicesData.forEach((_, index) => {
      const indicator = document.createElement("div");
      indicator.className = "indicator";
      indicator.addEventListener("click", () => goToSlide(index));
      indicatorsContainer.appendChild(indicator);
    });

    updateCarousel();
    startAutoSlide();
  };

  // Update card positions and indicators
  const updateCarousel = () => {
    const cards = carouselTrack.querySelectorAll(".service-card");
    const indicators = indicatorsContainer.querySelectorAll(".indicator");
    const totalCards = servicesData.length;
    const prevIndex = (currentIndex - 1 + totalCards) % totalCards;
    const nextIndex = (currentIndex + 1) % totalCards;

    cards.forEach((card, index) => {
      card.classList.remove("center", "left", "right", "hidden");
      if (index === currentIndex) card.classList.add("center");
      else if (index === prevIndex) card.classList.add("left");
      else if (index === nextIndex) card.classList.add("right");
      else card.classList.add("hidden");
    });

    indicators.forEach((indicator, index) => {
      indicator.classList.toggle("active", index === currentIndex);
    });
  };

  const goToSlide = (index) => {
    currentIndex = index;
    updateCarousel();
    resetAutoSlide();
  };

  window.nextSlide = () => goToSlide((currentIndex + 1) % servicesData.length);

  window.prevSlide = () =>
    goToSlide((currentIndex - 1 + servicesData.length) % servicesData.length);

  const startAutoSlide = () => {
    clearInterval(autoSlideInterval);
    if (!modal.classList.contains("show")) {
      autoSlideInterval = setInterval(window.nextSlide, 4000);
    }
  };

  const resetAutoSlide = () => startAutoSlide();

  // Modal functions
  const openModal = (service) => {
    document.getElementById("modalImage").src = service.image;
    document.getElementById(
      "modalTitle"
    ).innerHTML = `<i class="${service.icon}"></i> ${service.title}`;
    document.getElementById("modalInfo").textContent = service.info;
    modal.classList.add("show");
    document.body.style.overflow = "hidden";
    clearInterval(autoSlideInterval);
  };

  window.closeModal = () => {
    modal.classList.remove("show");
    document.body.style.overflow = "auto";
    startAutoSlide();
  };

  modal.addEventListener("click", (e) => {
    if (e.target === modal) window.closeModal();
  });
  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape" && modal.classList.contains("show"))
      window.closeModal();
  });

  // Pause auto-slide on hover
  if (carouselTrack) {
    carouselTrack.addEventListener("mouseenter", () =>
      clearInterval(autoSlideInterval)
    );
    carouselTrack.addEventListener("mouseleave", () => startAutoSlide());
  }

  // ===================================================
  // --- 3. GALLERY CAROUSEL & MODAL SCRIPT ---
  // (Functions nextGallerySlide, prevGallerySlide, etc. are defined globally below)
  // ===================================================
  const galleryImages = Array.from(
    { length: 32 },
    (_, i) => `/images/Projects/${i + 1}.jpeg`
  );

  let currentGalleryIndex = 0;
  let galleryAutoSlideInterval;
  let currentModalImageIndex = 0;
  let isZoomed = false;

  const galleryTrack = document.getElementById("galleryTrack");
  const galleryModal = document.getElementById("galleryModal");
  const modalGalleryImage = document.getElementById("modalGalleryImage");

  // Initialize Gallery
  const initGallery = () => {
    // Create gallery items
    if (!galleryTrack) return;
    galleryImages.forEach((image, index) => {
      const item = document.createElement("div");
      item.className = "gallery-item";

      const img = document.createElement("img");
      img.src = image;
      img.alt = `Project ${index + 1}`;
      img.loading = "lazy";

      item.appendChild(img);
      item.addEventListener("click", () => openGalleryModal(index));

      galleryTrack.appendChild(item);
    });

    updateGalleryCarousel();
    startGalleryAutoSlide();
  };

  const updateGalleryCarousel = () => {
    const items = galleryTrack.querySelectorAll(".gallery-item");
    if (items.length === 0) return;

    items.forEach((item, index) => {
      item.classList.remove("center", "left", "right", "hidden");

      const totalItems = galleryImages.length;
      const prevIndex = (currentGalleryIndex - 1 + totalItems) % totalItems;
      const nextIndex = (currentGalleryIndex + 1) % totalItems;

      if (index === currentGalleryIndex) {
        item.classList.add("center");
      } else if (index === prevIndex) {
        item.classList.add("left");
      } else if (index === nextIndex) {
        item.classList.add("right");
      } else {
        item.classList.add("hidden");
      }
    });
  };

  const goToGallerySlide = (index) => {
    currentGalleryIndex = index;
    updateGalleryCarousel();
    resetGalleryAutoSlide();
  };

  window.nextGallerySlide = () =>
    goToGallerySlide((currentGalleryIndex + 1) % galleryImages.length);

  window.prevGallerySlide = () =>
    goToGallerySlide(
      (currentGalleryIndex - 1 + galleryImages.length) % galleryImages.length
    );

  const startGalleryAutoSlide = () => {
    clearInterval(galleryAutoSlideInterval);
    // Only start if the gallery is present and modal is NOT open
    if (galleryModal && !galleryModal.classList.contains("show")) {
      galleryAutoSlideInterval = setInterval(window.nextGallerySlide, 3000);
    }
  };

  const resetGalleryAutoSlide = () => startGalleryAutoSlide();

  // Modal Functions
  const openGalleryModal = (index) => {
    currentModalImageIndex = index;
    modalGalleryImage.src = galleryImages[currentModalImageIndex];
    modalGalleryImage.alt = `Project ${currentModalImageIndex + 1}`;
    modalGalleryImage.classList.remove("zoomed");
    isZoomed = false;
    galleryModal.classList.add("show");
    document.body.style.overflow = "hidden";
    // Show zoom hint
    const zoomHint = document.getElementById("zoomHint");
    if (zoomHint) {
      zoomHint.style.animation = "none";
      setTimeout(() => {
        zoomHint.style.animation = "fadeInOut 3s ease-in-out";
      }, 100);
    }
    clearInterval(galleryAutoSlideInterval); // Pause gallery auto-slide
  };

  window.closeGalleryModal = (event) => {
    if (event) event.stopPropagation();
    galleryModal.classList.remove("show");
    document.body.style.overflow = "auto";
    modalGalleryImage.classList.remove("zoomed");
    isZoomed = false;
    startGalleryAutoSlide();
  };

  window.handleOverlayClick = (event) => {
    if (event.target === galleryModal) {
      window.closeGalleryModal();
    }
  };

  window.toggleZoom = (event) => {
    event.stopPropagation();
    isZoomed = !isZoomed;
    modalGalleryImage.classList.toggle("zoomed", isZoomed);
  };

  window.navigateModalImage = (direction, event) => {
    if (event) event.stopPropagation();

    currentModalImageIndex =
      (currentModalImageIndex + direction + galleryImages.length) %
      galleryImages.length;

    modalGalleryImage.classList.remove("zoomed");
    isZoomed = false;

    modalGalleryImage.style.opacity = 0;
    setTimeout(() => {
      modalGalleryImage.src = galleryImages[currentModalImageIndex];
      modalGalleryImage.alt = `Project ${currentModalImageIndex + 1}`;
      modalGalleryImage.style.opacity = 1;
    }, 150);
  };

  // Pause on hover
  if (galleryTrack) {
    galleryTrack.addEventListener("mouseenter", () =>
      clearInterval(galleryAutoSlideInterval)
    );
    galleryTrack.addEventListener("mouseleave", () => startGalleryAutoSlide());
  }

  // Keyboard navigation
  document.addEventListener("keydown", (e) => {
    if (galleryModal.classList.contains("show")) {
      if (e.key === "Escape") {
        window.closeGalleryModal();
      } else if (e.key === "ArrowLeft") {
        window.navigateModalImage(-1);
      } else if (e.key === "ArrowRight") {
        window.navigateModalImage(1);
      } else if (e.key === "z" || e.key === "Z" || e.key === " ") {
        window.toggleZoom(e);
      }
    }
  });

  // ===================================================
  // --- 4. GLOBAL INITIALIZATION ---
  // ===================================================

  // --- General Events ---
  document.addEventListener("keydown", (e) => {
    // Close mobile nav on Escape key press
    if (e.key === "Escape" && nav && nav.classList.contains("nav-active")) {
      toggleMobileNav();
    }
  });

  // --- Scroll Handler (Sticky Header) ---
  window.addEventListener("scroll", handleScrollAndMenu);
  handleScrollAndMenu(); // Run once on load to check initial position

  // --- Mobile Menu Toggles ---
  if (hamburger) {
    hamburger.addEventListener("click", toggleMobileNav);
  }

  // Close nav when a link is clicked
  navLinks.forEach((link) => {
    link.addEventListener("click", () => {
      if (nav && nav.classList.contains("nav-active")) {
        toggleMobileNav();
      }
    });
  });

  // Close nav when overlay is clicked
  if (bodyOverlay) {
    bodyOverlay.addEventListener("click", () => {
      if (nav && nav.classList.contains("nav-active")) {
        toggleMobileNav();
      }
    });
  }


  // --- Component Initialization ---
  populateBrandsCarousel();
  initServiceCarousel();
  initGallery();
});
